---
- user: name="{{ cif_user }}" shell=/bin/bash append=yes

- name: Ensure path has correct permissions
  file: path={{ cif_home }} owner={{ cif_user }} group={{ cif_group }} mode=0750

- name: Ensure user has a .profile
  copy:
    content: ""
    dest: "{{ cif_home }}/.profile"
    # Don't overwrite if it already exists
    force: false
    owner: "{{ cif_user }}"
    group: "{{ cif_group }}"
    mode: 0660
